name: PR

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Read .nvmrc
        run: echo "##[set-output name=nvmrc;]$(cat .nvmrc)"
        id: nvm
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ steps.nvm.outputs.nvmrc }}
      - run: npm i -g npm@8
      - run: npm ci
      - run: npm run typecheck
      - run: npm run format -- --check
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ["14", "16", "17", "18"]
    name: Test on Node ${{ matrix.node }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - run: npm i -g npm@8
      - run: npm ci
      - run: npm run test -- --coverage
      - name: coverage
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
  finish:
    needs: [formatting, test]
    runs-on: ubuntu-latest
    steps:
      - name: Coveralls finished
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.github_token }}
          parallel-finished: true
